FROM golang:1.26-alpine

RUN apk add --no-cache git
RUN go install github.com/air-verse/air@v1.61.7

WORKDIR /app

COPY proto/gen/go/ /proto/gen/go/
COPY auth/ /auth/
COPY report-service/go.mod report-service/go.sum* ./
RUN go mod download

COPY report-service/ .

EXPOSE 8080

CMD ["air"]
